### ISSUE TITLE
"Check for updates" doesn't work in the About box

### ISSUE THREAD

**Issue by MickeLind** [vovkos/ioninja-issues#1]
Only getting the error message "Error while checking for updates: Host tibbo.com not found"

**Comment by vovkos** [comment]
Which exact version is that (e.g. ioninja-3.8.3-windows-amd64)?

Also, could it be that tibbo.com is really not available from the machine you are running it on? Ping tibbo.com to make sure.

Another thing to try is downloading the update manifest manually; will it work? The update manifest is a simple text file located at:

http://tibbo.com/downloads/archive/ioninja/.ioninja-update-windows-amd64.txt

In the URL above, you can replace "windows" and "amd64" with OS and CPU of your machine, e.g. .ioninja-update-linux-x86.txt

Thing is, checking for updates is a simple HTTP GET implemented using the QNetworkAccessManager/QNetworkRequest facilities, and it never caused us problems in the past...

**Comment by MickeLind** [comment]
It is ioninja-3.8.3-windows-amd64, but it was the same with ioninja-3.8.0-windows-amd64.

I made a "ping tibbo.com" and got the respond "Ping request could not find host tibbo.com. Please check the name and try again."
BUT it is no problem to open "http://tibbo.com/downloads/archive/ioninja/.ioninja-update-windows-amd64.txt" in my Firefox...?!

How could that be, shouldn't the same DNS be called for the domain-resolving in both cases?

But perhaps I shouldn't be surprised, Bosch (where I'm working) has very restricted network policy...

**Comment by vovkos** [comment]
That's interesting. Well, Firefox and other browsers may use some specific proxy settings or may fall back to a global Mozilla or Google name server (such as ``8.8.8.8``) which would ultimately result in using a name server different from the one used by the socket API (such as ``gethostbyname``).

As a quick fix, try editing ``C:\Program Files\Tibbo\Ninja 3\conf\update.conf`` and replacing ``tibbo.com`` with its IP address ``93.174.104.89``

As a long-term solution, there are a couple of things we may do to combat that.

1) Add a setting to specify whether QT should use system proxy settings or not
2) Add a fall-back to a Google name server (e.g. ``8.8.8.8``) -- use it when DNS lookup fails
3) Add a fall-back to fixed IPs for ``tibbo.com`` and ``ioninja.com`` -- use those when DNS lookup fails

Let me know if a quick-fix via ``update.conf`` works for you.

**Comment by MickeLind** [comment]
It works outside Bosch network, so network issue...

**Comment by MickeLind** [comment]
I have tried the quick fix; replacing tibbo.com with its IP-address in update.conf... It worked!

**Comment by vovkos** [comment]
Great! I will probably still add some sort of fall-back mentioned above -- to make things work automatically in networks like yours.
