### ISSUE TITLE
tdevmon building fails on newer kernel.

### ISSUE THREAD

**Issue by thunder-weasel** [vovkos/ioninja-issues#11]
tdevmon building fails on newer kernel (5.6.12-1-MANJARO #1 SMP PREEMPT Sun May 10 14:36:43 UTC 2020 x86_64 GNU/Linux).

$ make
make -C /lib/modules/5.6.12-1-MANJARO/build/ M=/home/jpiel/build/ioninja/tdevmon-3.3.5-linux-amd64/share/tdevmon/src/lkm modules
make[1]: Entering directory '/usr/lib/modules/5.6.12-1-MANJARO/build'
  CC [M]  /home/jpiel/build/ioninja/tdevmon-3.3.5-linux-amd64/share/tdevmon/src/lkm/module.o
In file included from /home/jpiel/build/ioninja/tdevmon-3.3.5-linux-amd64/share/tdevmon/src/lkm/module.c:1:
/home/jpiel/build/ioninja/tdevmon-3.3.5-linux-amd64/share/tdevmon/src/lkm/pch.h: In function ‘ktime_get_real_ts’:
/home/jpiel/build/ioninja/tdevmon-3.3.5-linux-amd64/share/tdevmon/src/lkm/pch.h:46:4: error: dereferencing pointer to incomplete type ‘struct timespec’
   46 |  ts->tv_sec = (time_t)ts64.tv_sec;
      |    ^~
/home/jpiel/build/ioninja/tdevmon-3.3.5-linux-amd64/share/tdevmon/src/lkm/pch.h:46:16: error: ‘time_t’ undeclared (first use in this function); did you mean ‘ktime_t’?
   46 |  ts->tv_sec = (time_t)ts64.tv_sec;
      |                ^~~~~~
      |                ktime_t
/home/jpiel/build/ioninja/tdevmon-3.3.5-linux-amd64/share/tdevmon/src/lkm/pch.h:46:16: note: each undeclared identifier is reported only once for each function it appears in
/home/jpiel/build/ioninja/tdevmon-3.3.5-linux-amd64/share/tdevmon/src/lkm/pch.h:46:23: error: expected ‘;’ before ‘ts64’
   46 |  ts->tv_sec = (time_t)ts64.tv_sec;
      |                       ^~~~
      |                       ;
make[2]: *** [scripts/Makefile.build:268: /home/jpiel/build/ioninja/tdevmon-3.3.5-linux-amd64/share/tdevmon/src/lkm/module.o] Error 1
make[1]: *** [Makefile:1683: /home/jpiel/build/ioninja/tdevmon-3.3.5-linux-amd64/share/tdevmon/src/lkm] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.6.12-1-MANJARO/build'
make: *** [Makefile:16: default] Error 2

**Comment by vovkos** [comment]
Thanks for reporting. 

The issue apparently appeared on Linux-5.6.0 when they finally removed ``struct timespec`` from the kernel. Until we make an official release, please use the attached patch:

[timespec-patch.txt](https://github.com/vovkos/ioninja-issues/files/4676415/timespec-patch.txt)

```
$ cd ./share/tdevmon/src/lkm
$ patch -b -i timespec-patch.txt
```

**Comment by vovkos** [comment]
Fixed, closing
