### ISSUE TITLE
With timestamps off in settings, they still appear in the saved log

### ISSUE THREAD

**Issue by skot** [vovkos/ioninja-issues#12]
If I turn off timestamps in the settings under Log Engine, they are no longer shown in the main window. (This is good)

![image](https://user-images.githubusercontent.com/140785/83081695-1dfcb400-a036-11ea-9f67-f8c86f685c0b.png)

If I go to File -> Save Log As... and save my log as *.txt I still get timestamps in the saved txt file. I would like to have a saved log without timestamps.

This appears using the J-Link RTT plugin. I haven't tried with others..

**Comment by vovkos** [comment]
Good point, I received complaints about that behavior before. 

Should be fixed in the upcoming release.

**Comment by vovkos** [comment]
Fixed, closing
