### ISSUE TITLE
Problems with IO Ninja IDE on Netbeans 8.2

### ISSUE THREAD

**Issue by flobro30101** [vovkos/ioninja-issues#14]
After following instructions on IO Ninjas web site, I tried to create a new IO Ninja project (sample plugin) and there are no entries in the "Plugin Type" list box

Thanks

![image](https://user-images.githubusercontent.com/30126300/102108335-c9b5f780-3e00-11eb-9518-bb6076e0b569.png)

**Comment by vovkos** [comment]
Make sure the IO Ninja installation & configuration directories are specified correctly in the options.

![image](https://user-images.githubusercontent.com/1272029/102156644-edd50f80-3eb8-11eb-8e6b-671431f50393.png)

If you installed IO Ninja using a portable archive and into a non-standard directory (e.g. Downloads), please adjust accordingly.

**Comment by flobro30101** [comment]
Does it work on Linux?

There are no entries for the paths, and I cannot find any "tibbo"
directories...

Thanks

Floyd Brown
678.453.6069

**Comment by vovkos** [comment]
Yes, it works on Linux.

How did you install IO Ninja? If it was from a repository, then the default locations are ``/usr/bin/`` and ``/usr/etc/ioninja/``. If you installed it from a portable archive, just navigate to the corresponding ``$IONINJA/bin/`` and ``$IONINJA/etc/ioninja/`` directories, e.g.:

![image](https://user-images.githubusercontent.com/1272029/102297040-8a66e280-3f89-11eb-896f-e3c909a6556d.png)

**Comment by vovkos** [comment]
Apparently, the IDE doesn't suggest a correct default path for ``Conf Directory`` (should be ``/usr/etc/ioninja/``, not ``/etc/ioninja/``). We will fix that.

In any case, just specify paths according to where IO Ninja binaries and configuration files are on your machine.

**Comment by vovkos** [comment]
I assume that after manually configuring directories, everything worked for you. Closing the issue. The update for the IDE (to fix the default Conf Directory) was released today, too.
