### ISSUE TITLE
Ioninja freezes when the serial device is disconnected

### ISSUE THREAD

**Issue by Eitol** [vovkos/ioninja-issues#2]
Issue:
When a "Serial" session is created and connected to a device and it is physically disconnected from the equipment with the port open in IONinja, then the program freezes

SO: Ubuntu 17.10 x86_64

**Comment by vovkos** [comment]
I believe it's got broken after the Jancy IO library re-factoring two releases ago. As of now, it's working correctly on Windows, but not on Linux.

Should be fixed in the next release.

**Comment by vovkos** [comment]
This commit takes care of the issue:
https://github.com/vovkos/jancy/commit/e0a656a2fa228aa7632a4ed379794d04a08a164e

I will close this issue after the upcoming release next month.

**Comment by vovkos** [comment]
Fixed in v3.8.5
