### ISSUE TITLE
The "Transmit" button tabs have no "memory"

### ISSUE THREAD

**Issue by Eitol** [vovkos/ioninja-issues#3]
If several tabs are opened, when navigating between them, the tabs of the "Transmit" module (Text, Binaty and File) change and do not return to the state they were in when the tab was selected.
This causes the inconvenience of having to return to the mode that was selected before changing the tab,

**Comment by vovkos** [comment]
Good point. The Transmit pane doesn't behave quite intuitive when multiple sessions are opened. Actually, the bigger issue is that the data entered in one session is simply lost upon switching to another session (as it's being overwritten by the top of TX history stack).

In any case, I will try to polish that before the next release.

**Comment by vovkos** [comment]
Fixed in v3.8.5
