### ISSUE TITLE
ioninja does not run on CentOS 7

### ISSUE THREAD

**Issue by ghost** [vovkos/ioninja-issues#5]
Due to an unresolved libstdc++ dependency, the ioninja 64 bit rpm package is unable to run on CentOS 7.5

Test run:
```
$ ioninja
ioninja: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/bin/../lib/libjancy.so.1.8)
ioninja: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/bin/../lib/libjancy.so.1.8)
ioninja: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/bin/../lib/libjancy.so.1.8)
```

**Comment by vovkos** [comment]
I have rebuilt LLVM with -static-libstdc++, that should do the trick. Now libjancy has no dependency on libstdc++:

```
[vladimir@archlinux amd64]$ readelf -d libjancy.so.1.8.2 
Dynamic section at offset 0x133fb48 contains 31 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [librt.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libudev.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
 0x000000000000000e (SONAME)             Library soname: [libjancy.so.1.8]
```

The patch can be downloaded here:
https://github.com/vovkos/ioninja-issues/raw/master/patch/libjancy.tar.xz

If it works, I will rebuild the official packages.

**Comment by vovkos** [comment]
When building LLVM for the previous patch I have not set CMAKE_BUILD_TYPE to "Release". Try again (the link is the same: https://github.com/vovkos/ioninja-issues/raw/master/patch/libjancy.tar.xz)

**Comment by ghost** [comment]
Hi Vovkos. I did a quick test with your latest patch and it seems to do the trick. I haven't done any extensive tests, but at least the graphical interface starts.

**Comment by ghost** [comment]
Hi Vovkos

I did a quick test with your latest patch and it seems to do the trick. I haven't done any extensive tests, but at least the graphical interface starts.

Cheers
/Guido


On June 27, 2018 4:07:31 AM GMT+02:00, Vladimir Gladkov <notifications@github.com> wrote:
>When building LLVM for the previous patch I have not set
>CMAKE_BUILD_TYPE to "Release". Try again (the link is the same:
>https://github.com/vovkos/ioninja-issues/raw/master/patch/libjancy.tar.xz)
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/vovkos/ioninja-issues/issues/5#issuecomment-400519556

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by vovkos** [comment]
After more experiments, I found out that adding ``-static-libstdc++`` to LLVM is not necessary &mdash; adding it when building ``libjancy.so`` should be enough. Previously, it got lost because CMake incorrectly detected the language of the ``libjancy.so`` library as C, not C++ &mdash; as such, ``-static-libstdc++`` was not passed to the linker.

Forcing the library language to C++ solved the issue.

The last official release 3.9.0 contains ``libjancy.so`` without the dependency on ``libstdc++``
