### ISSUE TITLE
Windows Named Pipe Monitor: Process Names (not just PIDs)

### ISSUE THREAD

**Issue by mikeparker** [vovkos/ioninja-issues#8]
It would be nice to see the process names not just the PIDs in the log. 

I have the use case of a few processes interacting and it's a bit of a pain to have to look up the PIDs in the task manager every time I'm examining the logs. It also means pasting logs to other people is not as meaningful.

![image](https://user-images.githubusercontent.com/1557887/63446125-8bd5d880-c431-11e9-8fdb-394b5348892b.png)

**Comment by vovkos** [comment]
Good point and relatively easy to implement; we will try to schedule this for the next release.

**Comment by vovkos** [comment]
We are about to release a major update for IO Ninja; among many other things, it now can show process names in Pipe Monitor (the same goes for Mailslot Monitor and Serial Monitor). Take a look:

![pipemon-new](https://user-images.githubusercontent.com/1272029/70316859-88872100-1857-11ea-9080-f4f034fe095f.png)

The link to the internal build:
https://tibbo.com/downloads/archive/ioninja/.internal/ioninja-3.11.10-windows-amd64.7z

**Comment by vovkos** [comment]
The feature is implemented in the just-released ioninja-3.12.0
https://ioninja.com/downloads.html
