### ISSUE TITLE
Windows Named Pipe Monitor: filter behavior for uppercase letters

### ISSUE THREAD

**Issue by adenkiewicz** [vovkos/ioninja-issues#9]
The recently introduced filters for Named Pipes do not properly work with uppercase letters. Tested in 3.12.2.

I have process named CQPipesExplorer.exe (notice uppercase letters), when I try to filter for this process name, there are no results:
![image](https://user-images.githubusercontent.com/1060275/78231725-87979080-74d3-11ea-88e4-c8aa2ded505b.png)

If I change the name to lowercase only, it works:
![image](https://user-images.githubusercontent.com/1060275/78231793-a4cc5f00-74d3-11ea-85ab-fc220f957bff.png)

**Comment by vovkos** [comment]
Thanks for reporting the bug. Issue confirmed and will be fixed in the very next release.

**Comment by vovkos** [comment]
We have just release an update for IO Ninja (version 3.14.0)
Among other things, it should take care of this non-lowercase-wildcards issue.

Please download it at https://ioninja.com/downloads.html and let me know if it works for you.

**Comment by adenkiewicz** [comment]
Works as expected, thank you!
